### PR TITLE
OpenGL3 and build options for Linux

### PR DESCRIPTION
**Pull request by rtiemann**
So I did something... The first commit adds OpenGL3 support. I kept adding missing stuff until it worked, roughly following `SCsub` files and trying to do it the way it was done in the existing `meson.build` files. That version built with Meson seems to behave the same way now as the branched-off version from `master` built with SCons.

The second commit adds some missing options that are available in the SCons system, most notably the `use_sowrap` and related options. The `opengl3` and `vulkan` options are implemented now, too.

### CODE REVIEW

**Comment by jpakkane** [comment]
Thanks. Have you tested if this breaks things on Windows or macOS?

**Comment by rtiemann** [comment]
> Thanks. Have you tested if this breaks things on Windows or macOS?

I don't have any of them, so, no. Is it possible to test this reliably with a cross compiler? Should be easy enough to setup mingw. Or maybe I can manage to find an activation key for Windows so I could test at least for Windows in a VM.

**Comment by rtiemann** [comment]
I have installed the `mingw-w64-gcc` package (Arch Linux) which contains gcc 12.2.0, and adjusted the `cross/linux-mingw-win64` file to point at my `x86_64-w64-mingw32-gcc` etc. (there are no binaries with a `-posix` suffix).

Well, it failed to build, but so did the version without my patches. Here is the error message:

    FAILED: thirdparty/harfbuzz/libbuiltin_harfbuzz.a.p/src_hb-subset.cc.obj
    /usr/bin/x86_64-w64-mingw32-g++ -Ithirdparty/harfbuzz/libbuiltin_harfbuzz.a.p -Ithirdparty/harfbuzz -I../thirdparty/harfbuzz -I../thirdparty/harfbuzz/src -I../thirdparty/graphite/include -I../thirdparty/freetype/include -I../thirdparty/icu4c/common -I../thirdparty/icu4c/i18n -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -std=c++17 -O0 -g -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DTYPED_METHOD_BIND -DWINDOWS_ENABLED -D_DEBUG -DICU_DATA_NAME=icudt73l.dat -DFT2_BUILD_LIBRARY -DFT_CONFIG_OPTION_USE_PNG -DFT_CONFIG_OPTION_SYSTEM_ZLIB -DFT_CONFIG_OPTION_USE_BROTLI -DGRAPHITE2_NTRACING -DGRAPHITE2_NFILEFACE -DHAVE_ICU_BUILTIN -DHAVE_ICU -DHAVE_FREETYPE -DHAVE_GRAPHITE2 -DGRAPHITE2_STATIC -DHB_NO_PRAGMA_GCC_DIAGNOSTIC_WARNING -Wno-deprecated-declarations -MD -MQ thirdparty/harfbuzz/libbuiltin_harfbuzz.a.p/src_hb-subset.cc.obj -MF thirdparty/harfbuzz/libbuiltin_harfbuzz.a.p/src_hb-subset.cc.obj.d -o thirdparty/harfbuzz/libbuiltin_harfbuzz.a.p/src_hb-subset.cc.obj -c ../thirdparty/harfbuzz/src/hb-subset.cc
    /usr/lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/as: thirdparty/harfbuzz/libbuiltin_harfbuzz.a.p/src_hb-subset.cc.obj: too many sections (33021)
    /tmp/cc7iqwdK.s: Assembler messages:
    /tmp/cc7iqwdK.s: Fatal error: can't write 58 bytes to section .text of thirdparty/harfbuzz/libbuiltin_harfbuzz.a.p/src_hb-subset.cc.obj: 'file too big'
    /usr/lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/as: thirdparty/harfbuzz/libbuiltin_harfbuzz.a.p/src_hb-subset.cc.obj: too many sections (33021)
    /tmp/cc7iqwdK.s: Fatal error: thirdparty/harfbuzz/libbuiltin_harfbuzz.a.p/src_hb-subset.cc.obj: file too big

After some investigation, adding

    cpp_args = '-Wa,-mbig-obj'

to the `[properties]` section of the cross file fixed compilation. It is the first time I've ever encountered this problem (probably because it's Windows-specific), so I cannot tell if it would be a good idea to add the flag to your regular `cross/linux-mingw-win64` file.

Anyway, your branch compiles for Windows on my machine now, but final linking of `godot.exe` fails (undefined reference to `__imp_NtQueryInformationFile`, `CLSID_SpVoice`, `IID_ISpVoice`, `CLSID_SpObjectTokenCategory`, and `IID_ISpObjectTokenCategory`).

On my branch, however, the build fails much earlier when it tries to compile `thirdparty/glad/gl.c`. I hope to find some time soon to dig into this.

**Comment by jpakkane** [comment]
> Anyway, your branch compiles for Windows on my machine now, but final linking of godot.exe fails (undefined reference to __imp_NtQueryInformationFile, CLSID_SpVoice, IID_ISpVoice, CLSID_SpObjectTokenCategory, and IID_ISpObjectTokenCategory).

This has been fixed now.

You also need to add `#!/usr/bin/python3` at the top of `gles3_builders.py` for it to be detected as an executable on Windows.

**Comment by rtiemann** [comment]
Rebased and changed:
* I still had undefined references to `CLSID_SpVoice`, `IID_ISpVoice`, `CLSID_SpObjectTokenCategory`, and `IID_ISpObjectTokenCategory` when linking on Windows. Adding the `sapi` library fixed this.
* I've changed `gles3_builders.py` they way you suggested.
* The build succeeds with mingw now, with and without `opengl3`.

Unfortunately, `wine` doesn't start at all on my current system, even `winecfg` won't run. So I couldn't test if `godot.exe` can actually be executed.

**Comment by jpakkane** [comment]
I tried this and it fails on Windows. The reason for this is that `drivers\gles3\shaders\libmodule_gles3_shaders.a` is empty, because the target has no sources, only headers. MSVC does not like this and errors out. The correct solution here is to not build a library but instead put the headers in dependency sources.

**Comment by rtiemann** [comment]
Not building a library anymore. Still works with mingw, hopefully does with MSVC now.

**Comment by jpakkane** [comment]
Works. Thanks.

**Comment by rtiemann** [comment]
Thanks for merging.

Are there any features missing on your branch that would be worth porting and that I could help you with? Some options seem to be missing, but most of them are probably supported by Meson by other means anyway. Please let me know if you could use a helping hand.

**Comment by jpakkane** [comment]
All help is appreciated. For the moment the "best" thing to do would be to spread knowledge about this branch. The more people use it, the better chance it has on getting upstream. That would require a policy decision from the core devs and they seem to have deprioritised this during 4.0 release preparations.

**Pull request merged**
